DotNetThemeMVC/DotNetThemeMVC/Controllers/AdministratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DotNetThemeMVC.Controllers
{
    public class AdministratorController : Controller
    {
        // GET: Administrator/Home
        /// <summary>
        /// Displays the Administrator Home page. Providing quick links to perform all administrator actios.
        /// </summary>
        /// <returns>View</returns>
        [Authorize(Roles = "Administrators,SuperAdmin")]
        public ActionResult Home()
        {
            return View();
        }
        
        //Add additional Administratior Views here
    }
}

DotNetThemeMVC/DotNetThemeMVC/Views/Shared/_Footer.cshtml
<!-- start footer -->
<div class="footer" id="contact">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-3">
                <!-- address -->
                <address>
                    <h1><a href="https://www.wrdsb.ca/">Waterloo Region District School Board</a></h1>
                    <p>
                        51 Ardelt Avenue<br />
                        Kitchener, ON N2C 2R5
                    </p>

                    <p>
                        Switchboard: 519-570-0003<br />
                        <a href="http://www.wrdsb.ca/about-the-wrdsb/contact/">Contact Information</a>
                    </p>

                    <p><a href="http://www.wrdsb.ca/about-the-wrdsb/contact/website-feedback/">Website Feedback Form</a></p>
                </address>
                <div class="social-icons">              
                    <!-- Twitter -->
                    <iframe id="twitter-widget-0" scrolling="no" frameborder="0" allowtransparency="true" class="twitter-follow-button twitter-follow-button-rendered" title="Twitter Follow Button" src="https://platform.twitter.com/widgets/follow_button.5f60791584f95f2ec483faec8b16a58b.en.html#dnt=true&amp;id=twitter-widget-0&amp;lang=en&amp;screen_name=wrdsb&amp;show_count=false&amp;show_screen_name=true&amp;size=m&amp;time=1500322114929" style="position: static; visibility: visible; width: 107px; height: 20px;" data-screen-name="wrdsb"></iframe>
                    <script>!function (d, s, id) { var js, fjs = d.getElementsByTagName(s)[0], p = /^http:/.test(d.location) ? 'http' : 'https'; if (!d.getElementById(id)) { js = d.createElement(s); js.id = id; js.src = p + '://platform.twitter.com/widgets.js'; fjs.parentNode.insertBefore(js, fjs); } }(document, 'script', 'twitter-wjs');</script>
                    <!-- Instagram -->
                    <style>
                        .ig-b- {
                            display: inline-block;
                        }

                            .ig-b- img {
                                visibility: hidden;
                            }

                            .ig-b-:hover {
                                background-position: 0 -60px;
                            }

                            .ig-b-:active {
                                background-position: 0 -120px;
                            }

                        .ig-b-v-24 {
                            width: 137px;
                            height: 24px;
                            background: url(//badges.instagram.com/static/images/ig-badge-view-sprite-24.png) no-repeat 0 0;
                        }

                        @@media only screen and (-webkit-min-device-pixel-ratio: 2), only screen and (min--moz-device-pixel-ratio: 2), only screen and (-o-min-device-pixel-ratio: 2 / 1), only screen and (min-device-pixel-ratio: 2), only screen and (min-resolution: 192dpi), only screen and (min-resolution: 2dppx) {
                            .ig-b-v-24 {
                                background-image: url(//badges.instagram.com/static/images/ig-badge-view-sprite-24@2x.png);
                                background-size: 160px 178px;
                            }
                        }
                    </style>
                    <a href="https://www.instagram.com/wr_dsb/?ref=badge" class="ig-b- ig-b-v-24"><img src="//badges.instagram.com/static/images/ig-badge-view-24.png" alt="Instagram"></a>
                </div>
            </div>
            <div class="col-sm-6 col-md-3">
                <h1>Need Help?</h1>
                @if (@System.Web.Configuration.WebConfigurationManager.AppSettings["isInternal"] == "true")
                {
                    <!-- for internal applications or administrative screens
                    make sure you link to the direct link for a ticket -->
                    <p><a href="@System.Web.Configuration.WebConfigurationManager.AppSettings["servicedesk"].ToString()" target="_blank">Questions? Requests? ITService Desk!</a></p>
                }

                @if (@System.Web.Configuration.WebConfigurationManager.AppSettings["isInternal"] == "false")
                {
                <!-- for public facing applications or where help doesn't come through ITService Desk -->
                    <p>For comments, questions, or problems regarding @System.Web.Configuration.WebConfigurationManager.AppSettings["loginTitle"].ToString() contact us by calling or emailing us with a detailed description of your inquery.</p>
                    <p>
                        @System.Web.Configuration.WebConfigurationManager.AppSettings["owner"].ToString()<br />
                        Email: <a href="@System.Web.Configuration.WebConfigurationManager.AppSettings["ownerEmail"].ToString()">Contact Us</a><br />
                        Phone: @System.Web.Configuration.WebConfigurationManager.AppSettings["phone"].ToString()
                    </p>
                }
            </div>

            <!-- for internal applications or administrative screens
            make sure you link to the direct link for a ticket -->
            @if (@System.Web.Configuration.WebConfigurationManager.AppSettings["isInternal"] == "true")
            {
                <div class="col-sm-6 col-md-3">
                    <h1>Application Information</h1>
                    <h2>Owner</h2>
                    <p>@System.Web.Configuration.WebConfigurationManager.AppSettings["owner"].ToString()</p>
                    <p>Email: <a href="@System.Web.Configuration.WebConfigurationManager.AppSettings["ownerEmail"].ToString()">Contact Us</a></p>
                    <h2>Developer</h2>
                    <p>@System.Web.Configuration.WebConfigurationManager.AppSettings["developer"].ToString()</p>
                </div>
            }
            <div class="col-sm-12 col-md-3">
                <!--Space for more footer columns -->
            </div>
        </div>
    </div>
</div>

DotNetThemeMVC/DotNetThemeMVC/Views/Shared/_Footer_External.cshtml
<!-- start footer -->
<div class="footer" id="contact">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-3">
                <!-- address -->
                <address>
                    <h1><a href="https://www.wrdsb.ca/">Waterloo Region District School Board</a></h1>
                    <p>
                        51 Ardelt Avenue<br />
                        Kitchener, ON N2C 2R5
                    </p>

                    <p>
                        Switchboard: 519-570-0003<br />
                        <a href="http://www.wrdsb.ca/about-the-wrdsb/contact/">Contact Information</a>
                    </p>

                    <p><a href="http://www.wrdsb.ca/about-the-wrdsb/contact/website-feedback/">Website Feedback Form</a></p>
                </address>
                <div class="social-icons">
                    <!-- Twitter -->
                    <iframe id="twitter-widget-0" scrolling="no" frameborder="0" allowtransparency="true" class="twitter-follow-button twitter-follow-button-rendered" title="Twitter Follow Button" src="https://platform.twitter.com/widgets/follow_button.5f60791584f95f2ec483faec8b16a58b.en.html#dnt=true&amp;id=twitter-widget-0&amp;lang=en&amp;screen_name=wrdsb&amp;show_count=false&amp;show_screen_name=true&amp;size=m&amp;time=1500322114929" style="position: static; visibility: visible; width: 107px; height: 20px;" data-screen-name="wrdsb"></iframe>
                    <script>!function (d, s, id) { var js, fjs = d.getElementsByTagName(s)[0], p = /^http:/.test(d.location) ? 'http' : 'https'; if (!d.getElementById(id)) { js = d.createElement(s); js.id = id; js.src = p + '://platform.twitter.com/widgets.js'; fjs.parentNode.insertBefore(js, fjs); } }(document, 'script', 'twitter-wjs');</script>
                    <!-- Instagram -->
                    <style>
                        .ig-b- {
                            display: inline-block;
                        }

                            .ig-b- img {
                                visibility: hidden;
                            }

                            .ig-b-:hover {
                                background-position: 0 -60px;
                            }

                            .ig-b-:active {
                                background-position: 0 -120px;
                            }

                        .ig-b-v-24 {
                            width: 137px;
                            height: 24px;
                            background: url(//badges.instagram.com/static/images/ig-badge-view-sprite-24.png) no-repeat 0 0;
                        }

                        @@media only screen and (-webkit-min-device-pixel-ratio: 2), only screen and (min--moz-device-pixel-ratio: 2), only screen and (-o-min-device-pixel-ratio: 2 / 1), only screen and (min-device-pixel-ratio: 2), only screen and (min-resolution: 192dpi), only screen and (min-resolution: 2dppx) {
                            .ig-b-v-24 {
                                background-image: url(//badges.instagram.com/static/images/ig-badge-view-sprite-24@2x.png);
                                background-size: 160px 178px;
                            }
                        }
                    </style>
                    <a href="https://www.instagram.com/wr_dsb/?ref=badge" class="ig-b- ig-b-v-24"><img src="//badges.instagram.com/static/images/ig-badge-view-24.png" alt="Instagram"></a>
                </div>
            </div>
            <div class="col-sm-6 col-md-3">
                <h1>Need Help?</h1>
                @if (@System.Web.Configuration.WebConfigurationManager.AppSettings["isInternal"] == "true")
                {
                    <!-- for internal applications or administrative screens
                    make sure you link to the direct link for a ticket -->
                    <p><a href="@System.Web.Configuration.WebConfigurationManager.AppSettings["servicedesk"].ToString()" target="_blank">Questions? Requests? ITService Desk!</a></p>
                }

                @if (@System.Web.Configuration.WebConfigurationManager.AppSettings["isInternal"] == "false")
                {
                    <!-- for public facing applications or where help doesn't come through ITService Desk -->
                    <p>For comments, questions, or problems regarding @System.Web.Configuration.WebConfigurationManager.AppSettings["loginTitle"].ToString() contact us by calling or emailing us with a detailed description of your inquery.</p>
                    <p>
                        @System.Web.Configuration.WebConfigurationManager.AppSettings["owner"].ToString()<br />
                        Email: <a href="@System.Web.Configuration.WebConfigurationManager.AppSettings["ownerEmail"].ToString()">Contact Us</a><br />
                        Phone: @System.Web.Configuration.WebConfigurationManager.AppSettings["phone"].ToString()
                    </p>
                }
            </div>

            <!-- for internal applications or administrative screens
            make sure you link to the direct link for a ticket -->
            @if (@System.Web.Configuration.WebConfigurationManager.AppSettings["isInternal"] == "true")
            {
                <div class="col-sm-6 col-md-3">
                    <h1>Application Information</h1>
                    <h2>Owner</h2>
                    <p>@System.Web.Configuration.WebConfigurationManager.AppSettings["owner"].ToString()</p>
                    <p>Email: <a href="@System.Web.Configuration.WebConfigurationManager.AppSettings["ownerEmail"].ToString()">Contact Us</a></p>
                    <h2>Developer</h2>
                    <p>@System.Web.Configuration.WebConfigurationManager.AppSettings["developer"].ToString()</p>
                </div>
            }
            <div class="col-sm-12 col-md-3">
                <!--Space for more footer columns -->
            </div>
        </div>
    </div>
</div>

DotNetThemeMVC/DotNetThemeMVC/Views/Shared/_Footer_Internal.cshtml
<div id="footer" class="footer" role="contentinfo">
    <div id="fat-footer-container" class="container">

        <div class="row">
            <div class="col-sm-6 col-md-3" aria-labelledby="governance">
                <h1 id="footer-menu-governance">Governance</h1>
                <p><a id="footer-link-policies" style="color:white" href="https://staff.wrdsb.ca/board-policies/">Policies</a></p>
                <p><a id="footer-link-procedures" style="color:white" href="https://staff.wrdsb.ca/board-procedures/">Procedures</a></p>
                <p><a id="footer-link-protocols" style="color:white" href="https://staff.wrdsb.ca/board-protocols/">Protocols/Guidelines</a></p>
                <p><a id="footer-link-board-forms" style="color:white" href="https://staff.wrdsb.ca/board-forms/">Board Forms</a></p>
                <p><a id="footer-link-all-staff-notices" style="color:white" href="https://staff.wrdsb.ca/all-staff-notices/">All Staff Notices</a></p>
            </div>

            <div class="col-sm-6 col-md-3" aria-labelledby="g suite">
                <h1 id="footer-menu-g-suite">G Suite</h1>
                <p><a id="footer-link-google-mail" style="color:white" target="_blank" href="https://mail.google.com">Gmail</a></p>
                <p><a id="footer-link-google-calendar" style="color:white" target="_blank" href="https://calendar.google.com">Calendar</a></p>
                <p><a id="footer-link-google-drive" style="color:white" target="_blank" href="https://drive.google.com">Drive</a></p>
                <p><a id="footer-link-google-groups" style="color:white" target="_blank" href="https://groups.google.com">Groups</a></p>
                <p><a id="footer-link-g-suite-more" style="color:white" href="https://staff.wrdsb.ca/g-suite/">More...</a></p>
            </div>

            <div class="col-sm-6 col-md-3" aria-labelledby="">
                <h1 id="footer-menu-help">Help!</h1>
                <p><a id="footer-link-sds" style="color:white" target="_blank" href="https://msdsmanagement.msdsonline.com/company/ccc3134c-662d-499b-862d-39480a4688ed/">SDS Quick Search (MSDS)</a></p>
                <p><a id="footer-link-osbie" style="color:white" target="_blank" href="https://osbie.wrdsb.ca/">OSBIE Incident Reporting System</a></p>
                <p><a id="footer-link-help-desk" style="color:white" target="_blank" href="https://itservicedesk.wrdsb.ca/">ITService Desk (Help Desk)</a></p>
            </div>

            <div class="col-sm-6 col-md-3" aria-labelledby="">
                <h1 id="footer-menu-it-help">IT Help</h1>
                <p><a id="footer-link-password-reset" style="color:white" target="_blank" href="https://mypassword.wrdsb.ca/">Password Reset</a></p>
                <p><a id="footer-link-itservicedesk" style="color:white" target="_blank" href="https://itservicedesk.wrdsb.ca/">ITService Desk (Help Desk)</a></p>
                <p><a id="footer-link-wifi-docs" style="color:white" target="_blank" href="https://wifidocs.wrdsb.ca/">Wifi Docs</a></p>
                <p><a id="footer-link-it-help-more" style="color:white" href="https://staff.wrdsb.ca/its/">More...</a></p>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-6 col-md-3" aria-labelledby="">
                <h1 id="footer-menu-teachers">For Teachers</h1>
                <p><a id="footer-link-web-attendance" style="color:white" target="_blank" href="https://etrillium.wrdsb.ca/twebschool/TWEBATT/ptEntry.action?moduleId=TWEBATT">Trillium Web Attendance</a></p>
                <p><a id="footer-link-twea" style="color:white" target="_blank" href="https://etrillium.wrdsb.ca/trillium/">TWEA</a></p>
                <p><a id="footer-link-s4s" style="color:white" target="_blank" href="https://s4s.wrdsb.ca/">Support 4 Students (S4S)</a></p>
                <p><a id="footer-link-compass" style="color:white" target="_blank" href="https://compass.wrdsb.ca/portal/">Compass for Success (enCompass)</a></p>
                <p><a id="footer-link-d2l" style="color:white" target="_blank" href="http://wrdsb.elearningontario.ca/">Virtual Learning Environment (VLE/D2L)</a></p>
                <p><a id="footer-link-esl-tracker" style="color:white" target="_blank" href="https://etrillium.wrdsb.ca/twebboard/TWEBESL">ESL Tracker</a></p>
            </div>

            <div class="col-sm-6 col-md-3" aria-labelledby="">
                <h1 id="footer-menu-school-staff">For School Staff</h1>
                <p><a id="footer-link-trillium-report-centre" style="color:white" target="_blank" href="http://ec-oraapp1.wrdsb.ca:8888/forms/frmservlet?config=TRRP">Trillium Report Centre</a></p>
                <p><a id="footer-link-school-day" style="color:white" target="_blank" href="https://www.school-day.com/">School Day</a></p>
                <p><a id="footer-link-ssr" style="color:white" href="https://staff.wrdsb.ca/eguide/">Single Source Resource (eGuide)</a></p>
                <p><a id="footer-link-translations" style="color:white" href="https://staff.wrdsb.ca/resources6/translations/">Translations</a></p>
            </div>

            <div class="col-sm-6 col-md-3" aria-labelledby="">
                <h1 id="footer-menu-online-tools">Online Tools</h1>
                <p><a id="footer-link-staff-directory" style="color:white" href="https://staff.wrdsb.ca/directory/">Staff Directory</a></p>
                <p><a id="footer-link-calendars" style="color:white" href="https://staff.wrdsb.ca/calendar/">Calendars</a></p>
                <p><a id="footer-link-ess" style="color:white" target="_blank" href="https://ess.wrdsb.ca">Employee Self-Service Portal</a></p>
                <p><a id="footer-link-mental-health" style="color:white" target="_blank" href="https://staff.wrdsb.ca/mental-health/">Mental Health</a></p>
                <p><a id="footer-link-online-tools-more" style="color:white" href="https://staff.wrdsb.ca/online-tools/">More...</a></p>
            </div>

            <div class="col-sm-6 col-md-3" aria-labelledby="">
                <h1 id="footer-menu-training">Training and PD</h1>
                <p><a id="footer-link-oetc" style="color:white" target="_blank" href="https://training.wrdsb.ca">Online Employee Training Centre</a></p>
                <p><a id="footer-link-pd-place" style="color:white" target="_blank" href="http://wrdsb.pdplace.com/">PD Place</a></p>
                <p><a id="footer-link-equity" style="color:white" href="">Equity and Inclusion</a></p>
                <p><a id="footer-link-ntip" style="color:white" href="https://staff.wrdsb.ca/ntip/">New Teacher Induction Program (NTIP)</a></p>
                <p><a id="footer-link-training-more" style="color:white" href="https://staff.wrdsb.ca/training/">More...</a></p>
            </div>
        </div>

    </div>
</div>




<div class="container" id="loginbar" role="navigation" aria_labelledby="adminbar">
    <p id="adminbar" class="copyright" style="text-align: center;">
        @Html.ActionLink("Log off", "LogOff", "Account")
    </p>
</div>

DotNetThemeMVC/DotNetThemeMVC/Views/Shared/_Header_External.cshtml
<title>@System.Web.Configuration.WebConfigurationManager.AppSettings["title"].ToString()</title>

<link href="https://s3.amazonaws.com/wrdsb-ui-assets/public/master.css" rel="stylesheet"/>

<div id="masthead">
    <div class="container-top">
        <div class="header">
            <div class="container">
                <div class="row">
                    <div class="col-md-9 col-sm-8">
                        <div id="logo" role="heading">
                            <a aria-labelledby="logo" href="@System.Web.Configuration.WebConfigurationManager.AppSettings["appurl"].ToString()">
                                <span>Waterloo Region District School Board</span>
                            </a>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4">
                        <div class="staff-shortcuts" role="complementary" aria-labelledby="staff-shortcut-list">
                            <div class="searchbox" role="search" aria-labelledby="search">
                                <!--
                                <form action="https://wwwwrdsbdev.wpengine.com/" method="get">
                                    <input aria-label="Search" type="text" name="s" id="search" value="" placeholder="Search">
                                </form>-->
                            </div>

                            <div id="staff-shortcut-list">
                                <a href="#address">Contact Information</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar my-navbar" role="navigation" aria-labelledby="navbar-header">
        <div id="navbar-header">
            <!--
            <button type="button" class="navbar-toggle togglesearch" data-toggle="collapse" data-target=".navbar-search">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-search"><img src="https://wrdsb-ui-assets.s3.amazonaws.com/public/2/2.0.0/images/search.gif" style="width: 25px; height: 25px;"></span>
            </button>-->
            <button type="button" class="navbar-toggle togglenav" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="https://wwwwrdsbdev.wpengine.com/"> Waterloo Region<br> District School Board</a>
        </div>

        <div class="collapse navbar-search" role="search" aria-labelledby="mobileSearch">
            <!--
            <form action="https://wwwwrdsbdev.wpengine.com/" method="get">
                <input aria-label="Search" type="text" name="s" id="mobileSearch" value="" placeholder="Search">
            </form>-->
        </div>
        <div id="menu" class="container" role="navigation" aria_label="Menu">
            <div class="collapse navbar-collapse">
                <ul id="menu-top-menu" class="nav nav-justified">
                    <li id="home_link" class="menu-item current-menu-item current_page_item menu-item-home"><a title="Take me to the home page" href="@Url.Action("Index", "Home")">Home</a></li>
                    <li id="external_link" class="menu-item current-menu-item current_page_item menu-item-home"><a title="Take me to the external page" href="@Url.Action("External", "Home")">External</a></li>
                    <li id="internal_link" class="menu-item current-menu-item current_page_item menu-item-home"><a title="Take me to the internal page" href="@Url.Action("Internal", "Home")">Internal</a></li>
                </ul>
            </div>
        </div>
    </div><!-- /.navbar -->
</div>

DotNetThemeMVC/DotNetThemeMVC/Views/Shared/_Header_Internal.cshtml
<title>@System.Web.Configuration.WebConfigurationManager.AppSettings["title"].ToString()</title>

<link href="https://s3.amazonaws.com/wrdsb-ui-assets/intranet/master.css" rel="stylesheet" />

<div id="site-wide-navigation">

    <!-- persistent global navigation -->

    <div id="persistent-nav">
        <div class="mainlinks">
            <ul>
                <!--
                <li><a class="main" href="/">main</a></li>
                <li><a href="/sites/departments/">departments</a></li>
                <li><a href="/sites/guides/">guides</a></li>
                <li><a href="/sites/workspaces/">workspaces</a></li>
                <li><a href="/sites/school-handbooks/">school handbooks</a></li>
                -->
            </ul>
        </div>
        <div class="adminlinks">
            <ul>
                <!--
                <li><a href="https://staff-dev.wrdsb.io/wp-admin/">dashboard</a></li>
                <li><a href="https://staff-dev.wrdsb.io/wp-admin/profile.php">settings</a></li>-->
                <li>
                    @if (!User.IsInRole("Administrators"))
                    {
                        @Html.ActionLink("Account Settings", "Index", "Manage")
                    }
                </li>
                <li>@Html.ActionLink("Log off", "LogOff", "Account")</li>
            </ul>
        </div>
    </div>

    <!-- contextual navigation -->


</div>
<div class="container-top">
    <div id="masthead">
        <div class="header">
            <div class="container">
                <div class="row">
                    <div class="col-md-9 col-sm-8">
                        <div id="site_details" role="heading">
                            <p id="sitename"><span>WRDSB</span><br>@System.Web.Configuration.WebConfigurationManager.AppSettings["title"].ToString()</p>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4">
                        <div class="staff-shortcuts" role="complementary" aria-labelledby="staff-shortcut-list">
                            
                            <div class="searchbox" role="search" aria-labelledby="search">
                                <!--
                                <form action="https://staff-dev.wrdsb.io/" method="get">
                                    <input aria-label="Search" type="text" name="s" id="search" value="" placeholder="Search">
                                </form>-->
                            </div>
                            <div id="staff-shortcut-list">
                                <a href="https://gmail.google.com/" target="_blank" rel="noopener"><img src="https://wrdsb-ui-assets.s3.amazonaws.com/1/1.1.0/images/gmail.svg"></a><a href="https://drive.google.com/" target="_blank" rel="noopener"><img src="https://wrdsb-ui-assets.s3.amazonaws.com/1/1.1.0/images/drive.svg"></a><a href="https://calendar.google.com/" target="_blank" rel="noopener"><img src="https://wrdsb-ui-assets.s3.amazonaws.com/1/1.1.0/images/calendar.svg"></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- /.masthead -->
    <div class="navbar my-navbar" role="navigation" aria-labelledby="navbar-header">

        <div id="menu" class="container" role="navigation" aria_label="Menu">
            <div class="collapse navbar-collapse">
                <ul id="menu-top-menu" class="nav nav-justified">
                    <li id="home_link" class="menu-item current-menu-item current_page_item menu-item-home"><a title="Take me to the home page" href="@Url.Action("Index", "Home")">Home</a></li>
                    <li id="external_link" class="menu-item current-menu-item current_page_item menu-item-home"><a title="Take me to the external page" href="@Url.Action("External", "Home")">External</a></li>
                    <li id="internal_link" class="menu-item current-menu-item current_page_item menu-item-home"><a title="Take me to the internal page" href="@Url.Action("Internal", "Home")">Internal</a></li>
                    @if (User.IsInRole("Administrators") || User.IsInRole("SuperAdmin"))
                    {
                        <li id="admin_link" class="menu-item menu-item-type-post_type menu-item-object-page"><a title="Take me to the admin page" href="@Url.Action("Home", "Administrator")">Administrators</a></li>
                    }
                </ul>
            </div>
        </div>
    </div> <!-- /.navbar -->
</div>

DotNetThemeMVC/DotNetThemeMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    @Html.Partial("_Header")

    <title>WRDSB</title>

</head>
<body>
    <div class="container">
        @RenderBody()
    </div>
    @Html.Partial("_Footer")
</body>

</html>
@RenderSection("scripts", required: false)

DotNetThemeMVC/DotNetThemeMVC/Views/Shared/_Layout_External.cshtml
<!DOCTYPE html>
<html>
<head>
    @Html.Partial("_Header_External")

    <title>WRDSB</title>

</head>
<body>
    <div class="container">
        @RenderBody()
    </div>
    @Html.Partial("_Footer_External")
</body>

</html>
@RenderSection("scripts", required: false)

DotNetThemeMVC/DotNetThemeMVC/Views/Shared/_Layout_Internal.cshtml
<!DOCTYPE html>
<html>
<head>
    @Html.Partial("_Header_Internal")

    <title>WRDSB</title>

</head>
<body>
    <div class="container">
        @RenderBody()
    </div>
    @Html.Partial("_Footer_Internal")
</body>

</html>
@RenderSection("scripts", required: false)

DotNetThemeMVC/DotNetThemeMVC/Views/Shared/_ValidationSummary.cshtml
@model ModelStateDictionary
<!-- Created an custom view to override the way validation summary is rendered -->
@if (!Model.IsValid)
{
    <div class="alert alert-danger" role="alert">
        @foreach (var modelError in
                     Model.SelectMany(keyValuePair => keyValuePair.Value.Errors))
        {
            @modelError.ErrorMessage
        }
    </div>
}