DotNetThemeMVC/DotNetThemeMVC/Models/ADGroupRolesViewModel.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;

namespace DotNetThemeMVC.Models
{
    public class ADGroupRolesViewModel
    {
        public string groupName { get; set; }
        public List<string> groupRoles { get; set; }
        public List<string> allRoles { get; set; }
    }
}

DotNetThemeMVC/DotNetThemeMVC/Models/ad_group_roles.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetThemeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ad_group_roles
    {
        public int id { get; set; }
        public string group_name { get; set; }
        public string role_name { get; set; }
    }
}

DotNetThemeMVC/DotNetThemeMVC/Controllers/UserRoleController.cs
using DotNetThemeMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Microsoft.AspNet.Identity;
using System.Collections.ObjectModel;
using Microsoft.AspNet.Identity.EntityFramework;
using PagedList;
using System.Net;
using System.DirectoryServices.AccountManagement;
using System.Web.Services;

namespace DotNetThemeMVC.Controllers
{
    public class UserRoleController : Controller
    {
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: UserRole/Index
        /// <summary>
        /// Displays the UserRole Index page listing all board users. Allows for searching or filtering the users.
        /// </summary>
        /// <param name="userViewModel">The User model</param>
        /// <returns>View</returns>
        [Authorize(Roles = "SuperAdmin,Administrators")]
        public ActionResult Index(UserViewModel userViewModel)
        {
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(new ApplicationDbContext()));

            //Get all board users
            var users = UserManager.Users.Where(x => !x.UserName.Contains("@")).ToList();

            //If the signed in users role is Administrators, filter out users whose role is SuperAdmin
            if (isAdministrator())
            {
                var superUsers = roleManager.Roles.Single(x => x.Name == "SuperAdmin").Users;
                foreach (var superUser in superUsers)
                {
                    users.RemoveAll(x => x.Id == superUser.UserId);
                }
            }

            //If there is a role filter,filter down the list unless it's All Roles option
            if (!String.IsNullOrEmpty(userViewModel.roleFilter) && !userViewModel.roleFilter.Equals("All Roles"))
            {
                var roleUsers = roleManager.Roles.Single(x => x.Name.Equals(userViewModel.roleFilter)).Users;
                users = (from r in roleUsers join u in users on r.UserId equals u.Id select u).Distinct().ToList();
            }

            //If there is a search term, filter down the list
            if (!String.IsNullOrEmpty(userViewModel.searchString))
            {
                users = users.Where(x => x.UserName.Contains(userViewModel.searchString)).ToList();
            }

            //Sort the list
            switch (userViewModel.sortOrder)
            {
                case "name_desc":
                    users = users.OrderByDescending(x => x.UserName).ToList();
                    break;
                default:
                    users = users.OrderBy(x => x.UserName).ToList();
                    break;
            }

            var model = new Collection<UserRoleViewModel>();

            //All filtering has been completed on the user list.
            //Get the Roles for every user, pass it into the Model and then to the ViewModel.
            foreach (var user in users)
            {
                var userRoles = UserManager.GetRoles(user.Id);
                model.Add(new UserRoleViewModel { User = user, userRoles = userRoles });
            }

            //Set the default page
            if (userViewModel.page == 0)
            {
                userViewModel.page = 1;
            }
            //Set the default page size
            if (userViewModel.pageSize == 0)
            {
                userViewModel.pageSize = 10;
            }

            //Change it to a MVC Paged List
            userViewModel.Users = model.ToPagedList(userViewModel.page, userViewModel.pageSize);

            //Get the options for the Roles Filter drop down and the Page Size drop down
            ViewBag.PageSize = getPageOptions();
            ViewBag.UserRoles = getRoleFilterOptions();

            return View(userViewModel);
        }

        // GET: UserRole/Create
        /// <summary>
        /// Displays the UserRole Add page allowing administrator to add a board user to the db.
        /// </summary>
        /// <returns>View</returns>
        [Authorize(Roles = "SuperAdmin,Administrators")]
        public ActionResult Create()
        {
            UserRoleViewModel model = new UserRoleViewModel();
            model.allRoles = getRoleNames();
            model.userRoles = new List<string> { };
            return View(model);
        }

        // POST: UserRole/Create
        /// <summary>
        /// Adds a board user to the db. Creates the Identity account and grants the selected role.
        /// </summary>
        /// <param name="model">The User model</param>
        /// <returns>View</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SuperAdmin,Administrators")]
        public ActionResult Create(UserRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (UserManager.FindByName(model.User.UserName) == null)
                {
                    var email = getADEmail(model.User.UserName);

                    if (String.IsNullOrEmpty(email))
                    {
                        ModelState.AddModelError(model.User.UserName, "Failed to retrieve email for username from Active Directory");
                        model.allRoles = getRoleNames();
                        return View(model);
                    }
                    var user = new ApplicationUser { UserName = model.User.UserName, Email = email, EmailConfirmed = true };
                    var result = UserManager.Create(user);

                    //Assign the Roles
                    if (model.userRoles != null)
                    {
                        foreach (var role in model.userRoles)
                        {
                            UserManager.AddToRole(user.Id, role);
                        }
                    }
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(model.User.UserName, "This user exists.");
                    model.allRoles = getRoleNames();
                    return View(model);
                }
            }
            return View(model);
        }

        // GET: UserRole/Edit/5
        /// <summary>
        /// Displays the Userrole Edit page allowing the administrator to edit an existing board users information.
        /// </summary>
        /// <param name="id">The id of the board user to edit</param>
        /// <returns>View</returns>
        [Authorize(Roles = "SuperAdmin,Administrators")]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(new ApplicationDbContext()));
            ApplicationUser user = UserManager.Users.Where(x => x.Id == id).First();
            if (user == null)
            {
                return HttpNotFound();
            }
            UserRoleViewModel model = new UserRoleViewModel();

            //Get a List of Roles Names for the given user id
            model.userRoles = UserManager.GetRoles(id);

            //Get the entire list of Role Names
            model.allRoles = getRoleNames();

            var userRoles = UserManager.GetRoles(id);
            model.User = user;

            if (UserManager.IsInRole(id, "SuperAdmin") && isAdministrator())
            {
                return HttpNotFound();
            }
            return View(model);
        }

        // POST: UserRole/Edit/5
        /// <summary>
        /// Saves the changes of the board user to the db.
        /// </summary>
        /// <param name="model">The User model</param>
        /// <returns>View</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SuperAdmin,Administrators")]
        public ActionResult Edit(UserRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser user = UserManager.Users.Where(x => x.Id == model.User.Id).First();
                if (user.UserName != model.User.UserName)
                {
                    user.Email = getADEmail(model.User.UserName);
                    if (user.Email.Equals(""))
                    {
                        ModelState.AddModelError(model.User.UserName, "Cannot find the email address from AD for the given username.");

                        List<SelectListItem> allRoles = getRoles();
                        ViewBag.userRoles = allRoles;

                        return View(model);
                    }
                    user.UserName = model.User.UserName;
                    UserManager.Update(user);
                }

                //Update the Role Assignments
                var roles = UserManager.GetRoles(model.User.Id);
                UserManager.RemoveFromRoles(model.User.Id, roles.ToArray());
                if (model.userRoles != null)
                {
                    foreach (var userRole in model.userRoles)
                    {
                        UserManager.AddToRole(model.User.Id, userRole);
                    }
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }

        // GET: UserRole/Delete/5
        /// <summary>
        /// Displays the Board Users Delete page allowing administrator to delete a board user from the db.
        /// </summary>
        /// <param name="id">The id of the board user to delete</param>

DotNetThemeMVC/DotNetThemeMVC/Views/ADGroupRoles/Create.cshtml
@model DotNetThemeMVC.Models.ADGroupRolesViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="https://s3.amazonaws.com/wrdsb-theme/css/ui/jquery-ui.css" rel="stylesheet" />
<link href="https://s3.amazonaws.com/wrdsb-theme/css/ui/jquery.ui.base.css" rel="stylesheet" />
<link href="https://s3.amazonaws.com/wrdsb-theme/css/ui/jquery.ui.theme.css" rel="stylesheet" />
<link href="https://s3.amazonaws.com/wrdsb-theme/css/ui/jquery.ui.datepicker.css" rel="stylesheet" />
<link href="https://s3.amazonaws.com/wrdsb-theme/css/ui/jquery.ui.autocomplete.css" rel="stylesheet" />
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"
        integrity="sha256-0YPKAwZP7Mp3ALMRVB2i8GXeEndvCq3eSl/WsAl1Ryk="
        crossorigin="anonymous"></script>

<script>
    $(document).ready(function () {
        $("#searchTerms").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: '@Url.Action("getADGroups", "UserRole")',
                    type: 'POST',
                    dataType: 'json',
                    data: { search: request.term },
                    success: function (data) {
                        response($.map(data, function (item) {
                            return { label: item.value, value: item.value };
                        }));
                    }
                });
            },
            select: function (event, ui) {
                $("searchTerms").val(ui.item.label);
                document.getElementById("adGroupName").value = ui.item.label;
            }
        });
    });
</script>

<h2>Authorize a Group</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.groupName, new { id = "adGroupName"})
    @Html.Partial("_ValidationSummary", ViewData.ModelState)

    <fieldset>
        <legend>Active Directory Group Permissions</legend>
        <div class="col-md-3">
            <div class="form-group">
                @Html.LabelFor(model => model.groupName, "Active Directory Group Name")
                @Html.TextBoxFor(model => model.groupName, new { id = "searchTerms", Name = "searchTerms", placeholder = "Group Name", @class = "form-inline" })
                @Html.ValidationMessageFor(model => model.groupName, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.groupRoles, "Role")
                @Html.ListBoxFor(model => model.groupRoles, new SelectList(Model.allRoles), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.groupRoles, "", new { @class = "text-danger" })
            </div>
        </div>
    </fieldset>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" />
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DotNetThemeMVC/DotNetThemeMVC/Views/ADGroupRoles/Delete.cshtml
@model DotNetThemeMVC.Models.ADGroupRolesViewModel
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete the ACtive Directory Group and Roles</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.Hidden(Model.groupName)
    @Html.Partial("_ValidationSummary", ViewData.ModelState)

    <fieldset>
        <legend>Active Directory Group Permissions</legend>
        <div class="col-md-3">
            <div class="form-group">
                @Html.LabelFor(model => model.groupName, "Active Directory Group Name")<br />
                @Html.DisplayFor(model => model.groupName)
            </div>
            <div class="form-group">
                @foreach (var role in Model.groupRoles)
                {
                    @Html.DisplayFor(modelItem => role) @:
                }
            </div>
        </div>
    </fieldset>

    <h3>Are you sure you want to delete this?</h3>
    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" />
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DotNetThemeMVC/DotNetThemeMVC/Views/ADGroupRoles/Edit.cshtml
@model DotNetThemeMVC.Models.ADGroupRolesViewModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit the Active Directory Groups and Roles</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.Partial("_ValidationSummary", ViewData.ModelState)

    <fieldset>
        <legend>Active Directory Group Permissions</legend>
        <div class="col-md-3">
            <div class="form-group">
                @Html.LabelFor(model => model.groupName, "Active Directory Group Name")
                @Html.TextBoxFor(model => model.groupName, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.groupName, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.groupRoles, "Role")
                @Html.ListBoxFor(model => model.groupRoles, new SelectList(Model.allRoles), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.groupRoles, "", new { @class = "text-danger" })
            </div>
        </div>
    </fieldset>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DotNetThemeMVC/DotNetThemeMVC/Views/ADGroupRoles/Index.cshtml
@model IEnumerable<DotNetThemeMVC.Models.ADGroupRolesViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Active Directory Group Authorization Management</h1>

<div class="alert alert-warning">
    Depending on the number of users per group: creating, editing, or deleting their accounts or permissions may take a while.
</div>
<p>
    Manage which Active Directory Groups are authorized into this application and what roles the users of those groups recieve.
</p>
<div style="padding-top: 50px;">
    <table class="table table-condensed">
        <tr>
            <th>
                Active Directory Group
            </th>
            <th>
                Role
            </th>
            <th>
                Manage Groups @Html.ActionLink("(+)", "Create", null, htmlAttributes: new { @style = "color:green" })
            </th>
        </tr>


        @foreach (var item in Model)
        {
            <tr>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.groupName)
                </td>
                <td class="text-center">
                    @foreach (var role in item.groupRoles)
                    {
                        @Html.DisplayFor(modelItem => role) @:
                }
                </td>
                <td class="text-center">
                    @Html.ActionLink("Edit", "Edit", new { id = item.groupName }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.groupName })
                </td>
            </tr>
        }
    </table>
</div>